### ISSUE TITLE
oath2_json_decode_object error in 1.5.1

### ISSUE THREAD

**Issue by chris-crunchr** [OpenIDC/liboauth2#45]
I just tested 1.5.1 and it always fails for me with the error: `oauth2_json_decode_object: json_loads failed: '[' or '{' expected near '<'`. I'm doing nothing new as far as I'm aware (it fails regardless of the `verify.iss` setting):

```
OAuth2TokenVerify metadata https://{{ domain }}/.well-known/openid-configuration metadata.ssl_verify=false

...

<Location />
        AuthType oauth2
        Require valid-user
        OAuth2TargetPass remote_user_claim=preferred_username
</Location>
```

Generated a fresh token with KeyCloak.I modified the token a bit with jwt.io, but I can reproduce the problem with this token:

```
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InloTWpPd0p4VXljOXhUdFRkcUtHd3dReG1EU29UQkdVY0tkRXZUd0xCcmcifQ.eyJleHAiOjE2ODI5Nzg2MDYsImlhdCI6MTY4MTk3ODYwNiwianRpIjoiaWQiLCJpc3MiOiJteWlzc3VlciIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJteXN1YiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFwaSIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib25lIiwidHdvIiwidGhyZWUiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm9uZSIsInR3byIsInRocmVlIl19fSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiY2xpZW50SWQiOiJhcGkiLCJjbGllbnRIb3N0IjoiMTI3LjAuMC4xIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJncm91cHMiOlsiZ3JvdXAxIiwiZ3JvdXAyIiwiZ3JvdXAzIl0sInByZWZlcnJlZF91c2VybmFtZSI6InNlcnZpY2UtYWNjb3VudC1hcGkiLCJjbGllbnRBZGRyZXNzIjoiMTI3LjAuMC4xIn0.K9cK29xpkY0CCMBTE2W-zEIbj2FruW-f2a6WyM7Hu970znxVHiSoVb15aSt7mSKHWY-9iHqk_h_HQSFHxUL_EMUcS0hKAD-cwFif1jK4ZT0fP9vxIsuaU0G1TFd7xMQrY42CNdR1_tXHb9FdZmn7-ycArYOJ54w1noU2--6J7FY4G-fy5hGB-YroMisodr5ysnhhdHtW3W7Ci8HduqPJ-ueZ1uPIjB9kILY2A4N2kVIs3wa-xOBATOF3EMvJx6QZliRmmXxppPcMFlz3YWD-JXTt8s8k9EQEVzbyXqeJHMBaXFDsc6Em5RM4brGgEqXmh7IbpSAoq9-7rcN2Vk6rQA
```

I would build and test for you, once you have a patch, but I'm not sure what the quickest way is to build for a specific platform (I'm running ubuntu 22.04 locally, while our servers run 20.04). I could build on one of our test servers, if there is no other solution. Please let me know.

**Comment by zandbelt** [comment]
can you show more entity leading up to this?

**Comment by chris-crunchr** [comment]
There are no other errors/warning, but will try with debugging enabled.

**Comment by zandbelt** [comment]
my best guess is that the metadata endpoint is returning HTML instead of JSON
