### ISSUE TITLE
HTTP basic authentication may violate spec

### ISSUE THREAD

**Issue by jlabue-viewpoint** [OpenIDC/liboauth2#52]
When a token is requested using Basic as the authentication type, it is possible for no realm be indicated in the resulting HTTP response. This causes unpredictable behavior in applications that are attempting to process the response.

With Basic authentication, a realm value [is required](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate#basic). 

Found using Apache, but may occur on NGINX as well (did not verify)

**Comment by codespearhead** [comment]
This behavior indeed violates the specification.

[Appendix A from rfc7235](https://datatracker.ietf.org/doc/html/rfc7235#appendix-A) says;

> The "realm" parameter is no longer always required on challenges; consequently, the ABNF allows challenges without any auth parameters.

That specification, which updates rfc2617, is from June 2014.

[Section 2 of rfc7617](https://datatracker.ietf.org/doc/html/rfc7617#section-2), which was released in September 2015 and supersedes rfc2617, says:

> The 'Basic' Authentication Scheme
> [...]
> In challenges:
> [...]
> The authentication parameter 'realm' is REQUIRED.

**Comment by zandbelt** [comment]
this can be configured on the server level, independent of liboauth2 i.e. in Apache
```apache
AuthName <realm>
```

**Comment by jlabue-viewpoint** [comment]
I totally missed that. Thank you for the clarification!
