### ISSUE TITLE
Add the possibility to specify a custom string for the introspection request token field.

### ISSUE THREAD

**Issue by scommerot** [OpenIDC/liboauth2#57]
As in mod_auth_openidc log:
1/21/2015
- add support for OIDCOAuthIntrospectionTokenParamName (incl. Google OAuth 2.0 access token validation)
- add a sample OAuth 2.0 config for Google access tokens to README.md
- release 1.7.2

That's missing in this library it seems.

Please add the support to provide a custom token request value so the Google Oauth2.0 access token validation.
Google IDP expects the token added after the "access_token" keyword, but seems only "token" is supported in this library.
I understand rfc7662 says the value should be token and I did saw https://github.com/OpenIDC/mod_oauth2/issues/45.

However, I'd expect new versions to be somewhat feature complete and not break existing configurations when you attempt to upgrade them.

Thanks in advance.

**Comment by zandbelt** [comment]
now released in 2.1.0 https://github.com/OpenIDC/liboauth2/releases/tag/v2.1.0
